name: Build and Release Go Binary
on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.24'
  CGO_ENABLED: 0
  VERSION: ${{ github.ref_name }}

jobs:
  release:
    name: Release Go Binary
    if: github.ref_type == 'tag' && github.repository == 'traefik/traefik'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:          
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Build
        id: build
        env:          
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go env GOOS
          go env GOARCH
          go build -o rickslow -v main.go
          ARCHIVE_FILE=rickslow-${GOOS}-${GOARCH}.tag.gz
          tar -czvf "${ARCHIVE_FILE}" rickslow
          echo archive_path=${ARCHIVE_FILE} >> $GITHUB_OUTPUT
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build.outputs.archive_path }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}